name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu Primeiro JOB"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Olá Leandro !!!!"
      - name: "Segunda ação"
        run: |
          echo "Criação do seu primeiro workflow !!!"
          echo "Legal, Bora"
      - name: "Scritpt em Python"
        run:
          variavel = "Ola Leandro"
          print(variavel)
        shell: python      
