name: primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu Primeiro JOB"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Olá Leandro !!!!"
      - name: "Segunda ação"
        run: |
          echo "Criação do seu primeiro workflow !!!"
          echo "Legal, Bora"
      - name: "Script em Python"
        run: |
          python -c "variavel = 'Olá Leandro'; print(variavel)"

  segundo-job:
    name: "Instalação do Ambiente NodeJS"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificação da versão do NodeJS atual"
        run: node --version
      - name: "Definição da versão v20.17.0 do NodeJS"
      - uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
      - name: "Verificação da versão do NodeJS depois da atualização"
        run: node --version
       
